[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "=0.2.78"
image = "0.23.14"
imageproc = "0.22.0"
image-base64 = "0.1.0"